### ISSUE TITLE
Add support for  HasValidSignature method

### ISSUE THREAD

**Issue by artemlos** [SerialKeyManager/SKM-Client-API-CPP#1]
Documentation in .NET API: https://api.serialkeymanager.com/html/M_SKM_V3_ExtensionMethods_HasValidSignature.htm

**Comment by svedi** [comment]
Done automatically when constructing RawLicenseKey I think, right?

**Comment by artemlos** [comment]
Correct, the Client API takes care of this during RawLicense construction (https://github.com/SerialKeyManager/SKM-Client-API-CPP/blob/082b1ab3a51cb6166ab621cf21b3f9d3f24b572d/SKM%20Client%20API/RawLicenseKey.hpp)
