### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by artemlos** [SerialKeyManager/SKM-Client-API-CPP#11]
There is a potential memory leak on in https://github.com/Cryptolens/cryptolens-cpp/blob/master/src/MachineCodeComputer_COM.cpp#L362

```cpp
size_t SHA1(basic_Error & e, std::wstring const& data, std::string & append)
{

   .
   .
   .

   if (!(pbHash = (BYTE*)malloc(dwHashLen)))

   .
   .
   .

}
```

`free(pbHash)` appears to be missing.

**Comment by svedi** [comment]
Fixed in 80a821257a6202f66394bbe3ad8587596d73fb36
