### ISSUE TITLE
No way to retrieve API error response messages

### ISSUE THREAD

**Issue by Squareys** [SerialKeyManager/SKM-Client-API-CPP#9]
Hi all,

just started integrating cryptolens into my desktop application. On `activate_floating`, the api returns:

```
"{\"result\":1,\"message\":\"No active subscription found. Please contact support.\"}"
```

Yet, all I get through the C++ API is a `cryptolens::errors::Main::UNKNOWN_SERVER_REPLY`. Ideally, there would be a way to retrieve the `"message"` with the error during activation, or this error could be handled more specifically.

Thanks and best,
Jonathan

**Comment by Squareys** [comment]
Sorry, just found this is documented here:
https://help.cryptolens.io/faq/index ("Troubleshooting API Errors")

**Comment by artemlos** [comment]
@Squareys thank you for your feedback!

The error message is relative new, previously the API would return "Unable to authenticate" when no subscription was attached to the account. The C++ library doesn't seem to recognize it.

@svedi maybe we could add this to the backlog of the next release?

@Squareys I noticed your account didn't automatically upgrade. I'm sorry about that. This is is now fixed, so everything should work again. Please let me know if you have any questions 👍

**Comment by Squareys** [comment]
@artemlos Thanks! I temporarily created another trial account in the meantime, as I did not expect such a quick response on a Sunday. I'll switch back to the original, then!

Thanks again for the insanely quick reply!

\* Edit: The switch was successful, everything works on the other again, thanks!

**Comment by svedi** [comment]
Sure, I'll add this to the backlog.
